chore
Signed-off-by: iGxnon <igxnon@gmail.com>

diff --git a/blog b/blog
--- a/blog
+++ b/blog
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [ -z "$(which zola)" ]; then
+    echo "zola not found, please install it first"
+    exit 1
+fi
+
 function gen_weekly() {
     title=${1-"周报"}
     lang=${2-"zh"}
